if (NOT IS_DIRECTORY "${CHECK_DIR}")
    message(STATUS "Copying from ${SRC_DIR} to ${DEST_DIR}")
    file(MAKE_DIRECTORY "${DEST_DIR}")
    file(COPY "${SRC_DIR}" DESTINATION "${DEST_DIR}")
else()
    message(STATUS "Destination ${CHECK_DIR} already exist - skipping copy")
endif()
